# Generated by Django 5.2.17 on 2026-08-08 16:41

import django.db.models.deletion
import django.utils.timezone
import pretalx.common.models.mixins
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0040_alter_event_settingsstore_unique_together'),
        ('submission', '0087_question_limit_teams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('kind', models.CharField(max_length=200)),
                ('aggregate_type', models.CharField(max_length=200)),
                ('aggregate_id', models.PositiveBigIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'abstract': False,
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PreviewRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='created', max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'abstract': False,
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('completion_criteria', models.TextField()),
                ('task_type', models.CharField(default='acknowledgement', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.submission')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speakerops.taskdefinition')),
            ],
            options={
                'abstract': False,
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransitionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('aggregate_type', models.CharField(max_length=200)),
                ('aggregate_id', models.PositiveBigIntegerField()),
                ('from_state', models.CharField(max_length=100)),
                ('to_state', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'abstract': False,
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CommandReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(max_length=200)),
                ('command', models.CharField(max_length=200)),
                ('aggregate_type', models.CharField(max_length=200)),
                ('aggregate_id', models.PositiveBigIntegerField()),
                ('result', models.JSONField(default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'key'), name='speakerops_receipt_event_key')],
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='taskdefinition',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='speakerops_definition_event_slug'),
        ),
    ]
