# Generated by Django 5.2.17 on 2026-08-08 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_alter_event_settingsstore_unique_together'),
        ('speakerops', '0001_initial'),
        ('submission', '0087_question_limit_teams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='onboardingtask',
            constraint=models.UniqueConstraint(fields=('submission', 'speaker', 'definition'), name='speakerops_task_submission_speaker_definition'),
        ),
    ]
