# Generated by Django 5.2.17 on 2026-08-08 16:49

import django.db.models.deletion
import django.utils.timezone
import pretalx.common.models.mixins
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_alter_event_settingsstore_unique_together'),
        ('speakerops', '0002_onboardingtask_speakerops_task_submission_speaker_definition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtask',
            name='accepted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='evidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='waiver_reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='taskdefinition',
            name='completion_evaluator',
            field=models.CharField(default='acknowledgement', max_length=60),
        ),
        migrations.AddField(
            model_name='taskdefinition',
            name='due_days_after_acceptance',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='taskdefinition',
            name='evaluator_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='taskdefinition',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='taskdefinition',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='speakerops.onboardingtemplate'),
        ),
        migrations.CreateModel(
            name='ReminderReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('reminder_key', models.CharField(max_length=160)),
                ('queued_mail_id', models.PositiveBigIntegerField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakerops.onboardingtask')),
            ],
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.PositiveIntegerField()),
                ('body_html', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='speakerops.resource')),
            ],
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('kind', models.CharField(max_length=50)),
                ('value', models.JSONField(default=dict)),
                ('upload', models.FileField(null=True, upload_to='speakerops/evidence/')),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='speakerops.onboardingtask')),
            ],
            options={
                'abstract': False,
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplate',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='speakerops_template_event_slug'),
        ),
        migrations.AddConstraint(
            model_name='reminderreceipt',
            constraint=models.UniqueConstraint(fields=('event', 'task', 'speaker', 'reminder_key'), name='speakerops_reminder_dedupe'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='speakerops_resource_event_slug'),
        ),
        migrations.AddConstraint(
            model_name='resourceversion',
            constraint=models.UniqueConstraint(fields=('resource', 'version'), name='speakerops_resource_version'),
        ),
    ]
