# Generated by Django 5.2.17 on 2026-08-08 16:58

import django.db.models.deletion
import django.utils.timezone
import pretalx.common.models.mixins
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_alter_event_settingsstore_unique_together'),
        ('speakerops', '0003_onboardingtask_accepted_at_onboardingtask_evidence_and_more'),
        ('submission', '0087_question_limit_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleIcsIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uid', models.CharField(max_length=300)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('fingerprint', models.CharField(max_length=64)),
                ('canceled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakerops_ics', to='submission.submission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'submission'), name='speakerops_ics_event_submission')],
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
