# Generated by Django 5.2.17 on 2026-08-08 17:05

import django.db.models.deletion
import django.utils.timezone
import pretalx.common.models.mixins
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_alter_event_settingsstore_unique_together'),
        ('speakerops', '0004_scheduleicsidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceleventsConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('base_url', models.URLField(default='http://mock-accelevents:9000')),
                ('event_url', models.SlugField(max_length=200)),
                ('credential_ref', models.CharField(max_length=200)),
                ('auth_header', models.CharField(default='Key', max_length=40)),
                ('status', models.CharField(default='credential_blocked', max_length=30)),
                ('last_error', models.TextField()),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'abstract': False,
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SyncItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(max_length=20)),
                ('local_type', models.CharField(max_length=40)),
                ('local_id', models.PositiveBigIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('external_id', models.CharField(max_length=120)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('request_id', models.CharField(max_length=120)),
                ('error', models.TextField()),
                ('version', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'abstract': False,
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SyncAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('request_id', models.CharField(max_length=120)),
                ('response', models.JSONField(default=dict)),
                ('error', models.TextField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_history', to='speakerops.syncitem')),
            ],
            options={
                'abstract': False,
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SyncPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='created', max_length=20)),
                ('fingerprint', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'abstract': False,
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='previewed', max_length=20)),
                ('version', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('preview', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='speakerops.syncpreview')),
            ],
            options={
                'abstract': False,
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='syncitem',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='speakerops.syncrun'),
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('local_type', models.CharField(max_length=40)),
                ('local_id', models.PositiveBigIntegerField()),
                ('external_id', models.CharField(max_length=120)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('reconciled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'local_type', 'local_id'), name='speakerops_external_identity')],
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('local_type', models.CharField(max_length=40)),
                ('mapping', models.JSONField(default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'local_type'), name='speakerops_mapping_event_type')],
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
