# Generated by Django 5.2.17 on 2026-08-08

import django.db.models.deletion
import pretalx.common.models.mixins
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0040_alter_event_settingsstore_unique_together"),
        ("speakerops", "0005_acceleventsconnection_syncitem_syncattempt_and_more"),
        ("submission", "0087_question_limit_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRecommendation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("strong_accept", "Strong accept"),
                            ("accept", "Accept"),
                            ("hold", "Discuss"),
                            ("reject", "Reject"),
                        ],
                        default="hold",
                        max_length=24,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.event",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakerops_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakerops_recommendations",
                        to="submission.submission",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "submission", "reviewer"),
                        name="speakerops_recommendation_event_submission_reviewer",
                    )
                ],
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
    ]
