# Generated by Django 5.2.17 on 2026-08-09 20:57

import django.db.models.deletion
import pretalx.common.models.mixins
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0040_alter_event_settingsstore_unique_together"),
        ("speakerops", "0014_historicaltalk_field_provenance"),
        ("submission", "0087_question_limit_teams"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationRound",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=160)),
                ("position", models.PositiveIntegerField(default=0)),
                ("opens_at", models.DateField()),
                ("closes_at", models.DateField()),
                ("blinded", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
            ],
            options={
                "ordering": ("position", "pk"),
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EvaluationCriterion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=160)),
                ("field_type", models.CharField(max_length=16)),
                ("position", models.PositiveIntegerField(default=0)),
                ("required", models.BooleanField(default=True)),
                ("weight", models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ("minimum", models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ("maximum", models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ("options", models.JSONField(default=list)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="speakerops.evaluationround",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "pk"),
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RoundReviewAssignment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("status", models.CharField(default="assigned", max_length=16)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("recusal_reason", models.TextField(default="")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakerops_round_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="speakerops.evaluationround",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakerops_round_assignments",
                        to="submission.submission",
                    ),
                ),
            ],
            options={
                "ordering": ("submission__title", "pk"),
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EvaluationAnswer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("numeric_value", models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ("choice_value", models.CharField(default="", max_length=160)),
                ("text_value", models.TextField(default="")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="speakerops.evaluationcriterion",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="speakerops.roundreviewassignment",
                    ),
                ),
            ],
            options={
                "ordering": ("criterion__position", "criterion_id"),
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RoundReviewer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("assignment_limit", models.PositiveIntegerField(default=5)),
                ("last_reminded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakerops_round_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_memberships",
                        to="speakerops.evaluationround",
                    ),
                ),
            ],
            options={
                "ordering": ("reviewer__name", "reviewer__email"),
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationround",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="speakerops_evaluation_round_event_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationcriterion",
            constraint=models.UniqueConstraint(
                fields=("round", "name"), name="speakerops_evaluation_criterion_round_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="roundreviewassignment",
            constraint=models.UniqueConstraint(
                fields=("round", "reviewer", "submission"),
                name="speakerops_round_assignment_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationanswer",
            constraint=models.UniqueConstraint(
                fields=("assignment", "criterion"),
                name="speakerops_evaluation_answer_assignment_criterion",
            ),
        ),
        migrations.AddConstraint(
            model_name="roundreviewer",
            constraint=models.UniqueConstraint(
                fields=("round", "reviewer"), name="speakerops_round_reviewer_unique"
            ),
        ),
    ]
