# Generated by Django 5.2.17 on 2026-08-09 21:23

import django.db.models.deletion
import django.utils.timezone
import pretalx.common.models.mixins
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0040_alter_event_settingsstore_unique_together"),
        ("speakerops", "0018_speaker_operations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMContact",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(default="", max_length=254)),
                ("company", models.CharField(default="", max_length=200)),
                ("job_title", models.CharField(default="", max_length=200)),
                ("headshot_url", models.URLField(default="")),
                ("biography", models.TextField(default="")),
                ("tags", models.JSONField(default=list)),
                ("internal_notes", models.TextField(default="")),
                (
                    "merged_into",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_contacts",
                        to="speakerops.crmcontact",
                    ),
                ),
                (
                    "organiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakerops_crm_contacts",
                        to="event.organiser",
                    ),
                ),
                (
                    "source_speaker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_contacts",
                        to="speakerops.historicalspeaker",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "email", "pk"),
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CRMEventLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="speakerops_crm_links_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_links",
                        to="speakerops.crmcontact",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_contacts",
                        to="event.event",
                    ),
                ),
                (
                    "organiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakerops_crm_event_links",
                        to="event.organiser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="speakerops_crm_event_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-added_at", "-pk"),
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CRMOutreachLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("subject", models.CharField(max_length=240)),
                ("rendered_body", models.TextField()),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach",
                        to="speakerops.crmcontact",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_outreach",
                        to="event.event",
                    ),
                ),
                (
                    "organiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakerops_crm_outreach",
                        to="event.organiser",
                    ),
                ),
            ],
            options={
                "ordering": ("-logged_at", "-pk"),
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CRMPipelineCard",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("stage", models.CharField(default="prospect", max_length=20)),
                ("notes", models.TextField(default="")),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_card",
                        to="speakerops.crmcontact",
                    ),
                ),
                (
                    "organiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakerops_crm_cards",
                        to="event.organiser",
                    ),
                ),
            ],
            options={
                "ordering": ("stage", "contact__name"),
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CRMPipelineHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("from_stage", models.CharField(default="", max_length=20)),
                ("to_stage", models.CharField(max_length=20)),
                ("note", models.TextField(default="")),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="speakerops.crmpipelinecard",
                    ),
                ),
            ],
            options={
                "ordering": ("-changed_at", "-pk"),
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CRMSegment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=160)),
                ("filter_definition", models.JSONField(default=dict)),
                (
                    "contacts",
                    models.ManyToManyField(related_name="segments", to="speakerops.crmcontact"),
                ),
                (
                    "organiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakerops_crm_segments",
                        to="event.organiser",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "pk"),
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
        migrations.AddIndex(
            model_name="crmcontact",
            index=models.Index(fields=["organiser", "name"], name="speakerops__organis_052436_idx"),
        ),
        migrations.AddIndex(
            model_name="crmcontact",
            index=models.Index(
                fields=["organiser", "email"], name="speakerops__organis_4890a8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="crmeventlink",
            constraint=models.UniqueConstraint(
                fields=("contact", "event"), name="speakerops_crm_contact_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="crmsegment",
            constraint=models.UniqueConstraint(
                fields=("organiser", "name"), name="speakerops_crm_segment_organiser_name"
            ),
        ),
    ]
