# Generated by Django 5.2.17 on 2026-08-09 23:29

import django.db.models.deletion
import django.utils.timezone
import pretalx.common.models.mixins
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakerops', '0019_organiser_crm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSourceIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('source_key', models.CharField(max_length=240)),
                ('display_name', models.CharField(max_length=200)),
                ('source_url', models.URLField()),
                ('source_updated_at', models.DateTimeField()),
                ('resolution_status', models.CharField(default='isolated', max_length=24)),
                ('active', models.BooleanField(default=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_identities', to='speakerops.conferenceedition')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_identities', to='speakerops.historicalspeaker')),
            ],
            options={
                'ordering': ('edition', 'display_name', 'source_key'),
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIdentityDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(max_length=16)),
                ('reason', models.TextField()),
                ('evidence_url', models.URLField()),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision_version', models.PositiveIntegerField(default=1)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speakerops_historical_identity_decisions', to=settings.AUTH_USER_MODEL)),
                ('prior_speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prior_identity_decisions', to='speakerops.historicalspeaker')),
                ('resolved_speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolved_identity_decisions', to='speakerops.historicalspeaker')),
                ('source_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='speakerops.historicalsourceidentity')),
            ],
            options={
                'ordering': ('-decided_at', '-decision_version', '-pk'),
            },
            bases=(pretalx.common.models.mixins.LogMixin, pretalx.common.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='historicalspeakercredit',
            name='source_identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='speakerops.historicalsourceidentity'),
        ),
        migrations.AddIndex(
            model_name='historicalsourceidentity',
            index=models.Index(fields=['edition', 'source_key'], name='speakerops__edition_ac9f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalsourceidentity',
            index=models.Index(fields=['display_name'], name='speakerops__display_fadfc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicalsourceidentity',
            constraint=models.UniqueConstraint(fields=('edition', 'source_key'), name='speakerops_source_identity_edition_key'),
        ),
        migrations.AddConstraint(
            model_name='historicalidentitydecision',
            constraint=models.UniqueConstraint(fields=('source_identity', 'decision_version'), name='speakerops_identity_decision_version'),
        ),
    ]
